//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B.SimpleBooking.Application.Services.ResultPattern.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("B.SimpleBooking.Application.Services.ResultPattern.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city cannot be empty..
        /// </summary>
        internal static string ADDRESS_CITY_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_CITY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city cannot exceed 50 characters..
        /// </summary>
        internal static string ADDRESS_CITY_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_CITY_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complement cannot exceed 50 characters..
        /// </summary>
        internal static string ADDRESS_COMPLEMENT_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_COMPLEMENT_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The neighborhood cannot be empty..
        /// </summary>
        internal static string ADDRESS_NEIGHBORHOOD_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_NEIGHBORHOOD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The neighborhood cannot exceed 50 characters..
        /// </summary>
        internal static string ADDRESS_NEIGHBORHOOD_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_NEIGHBORHOOD_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number cannot be empty..
        /// </summary>
        internal static string ADDRESS_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number cannot exceed 10 characters..
        /// </summary>
        internal static string ADDRESS_NUMBER_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_NUMBER_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state cannot be empty..
        /// </summary>
        internal static string ADDRESS_STATE_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_STATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state must be exactly 2 characters long..
        /// </summary>
        internal static string ADDRESS_STATE_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("ADDRESS_STATE_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street cannot be empty..
        /// </summary>
        internal static string ADDRESS_STREET_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_STREET_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street cannot exceed 100 characters..
        /// </summary>
        internal static string ADDRESS_STREET_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_STREET_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zip code cannot be empty..
        /// </summary>
        internal static string ADDRESS_ZIPCODE_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_ZIPCODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zip code cannot exceed 10 characters..
        /// </summary>
        internal static string ADDRESS_ZIPCODE_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_ZIPCODE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description cannot be empty..
        /// </summary>
        internal static string DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description cannot exceed 500 characters..
        /// </summary>
        internal static string DESCRIPTION_TOO_LONG {
            get {
                return ResourceManager.GetString("DESCRIPTION_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description must be at least 10 characters long..
        /// </summary>
        internal static string DESCRIPTION_TOO_SHORT {
            get {
                return ResourceManager.GetString("DESCRIPTION_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email cannot be empty..
        /// </summary>
        internal static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is in an invalid format..
        /// </summary>
        internal static string EMAIL_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("EMAIL_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        internal static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot exceed 50 characters..
        /// </summary>
        internal static string NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be empty..
        /// </summary>
        internal static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one digit..
        /// </summary>
        internal static string PASSWORD_NO_DIGIT {
            get {
                return ResourceManager.GetString("PASSWORD_NO_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one lowercase letter..
        /// </summary>
        internal static string PASSWORD_NO_LOWERCASE {
            get {
                return ResourceManager.GetString("PASSWORD_NO_LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one special character..
        /// </summary>
        internal static string PASSWORD_NO_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("PASSWORD_NO_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one uppercase letter..
        /// </summary>
        internal static string PASSWORD_NO_UPPERCASE {
            get {
                return ResourceManager.GetString("PASSWORD_NO_UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too long..
        /// </summary>
        internal static string PASSWORD_TOO_LONG {
            get {
                return ResourceManager.GetString("PASSWORD_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 characters long..
        /// </summary>
        internal static string PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number cannot be empty..
        /// </summary>
        internal static string PHONE_EMPTY {
            get {
                return ResourceManager.GetString("PHONE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number must be in the format (XX) XXXXX-XXXX..
        /// </summary>
        internal static string PHONE_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("PHONE_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A professional with this email or phone number already exists..
        /// </summary>
        internal static string PROFESSIONAL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("PROFESSIONAL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and the professional cannot be created..
        /// </summary>
        internal static string PROFESSIONAL_CANNOT_BE_CREATED {
            get {
                return ResourceManager.GetString("PROFESSIONAL_CANNOT_BE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A professional with the specified ID was not found..
        /// </summary>
        internal static string PROFESSIONAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("PROFESSIONAL_NOT_FOUND", resourceCulture);
            }
        }
    }
}
